### ISSUE TITLE
transform-pouch bug breaks comdb when using couchdb

### ISSUE THREAD

**Issue by garbados** [garbados/comdb#15]
Transform-Pouch is [broken](https://github.com/pouchdb-community/transform-pouch/issues/54) against CouchDB, and as a result this occurs when running the CouchDB example in this repository:

```
$ node examples/couchdb.js 
...
TypeError: Cannot read property 'doc' of undefined
    at /home/garbados/code/comdb/examples/couchdb.js:40:12
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

There is a pending fix [here](https://github.com/pouchdb-community/transform-pouch/pull/56). The dependency in this project will need to be updated as soon as that patch lands.

**Comment by dheimoz** [comment]
hello @garbados , just wanted to let you know the fix has been merged.

**Comment by garbados** [comment]
Fixed!
