### ISSUE TITLE
Loading encrypted documents created with `.post()` fails sometimes

### ISSUE THREAD

**Issue by garbados** [garbados/comdb#21]
Encrypted documents created with `.post()` fail to load using `.loadEncrypted()` if a version of that document already exists on the decrypted side. You can replicate this issue in a browser by running this code:

```
const db = new PouchDB('local')
db.setPassword(PASSWORD).then(async () => {
  await db.loadEncrypted()
  await db.post({ name: 'bob' })
})
```

This will work the first time. But if you run this in a browser and then reload the page, it will fail with a message like this:

![](https://user-images.githubusercontent.com/10394611/146838353-fd26842e-34b8-4955-b3d6-41b2595187ed.png)

**Comment by garbados** [comment]
Hi @jjtolton ! A fix to your issue has been released in version `5.0.2-beta`. Check it out and let me know if anything went wrong!

**Comment by jjtolton** [comment]
I can’t WAIT to try it !  I’ll get you some feedback soon

**Comment by jjtolton** [comment]
Works GREAT!  Only thing now is you need to get that GH sponsors account open!
