### ISSUE TITLE
Fully encrypt PARTIALLY encrypted database

### ISSUE THREAD

**Issue by jjtolton** [garbados/comdb#30]
This is related to the excellent work in https://github.com/garbados/comdb/pull/28.

As part of a software update, I have a use case where I want to administratively deploy new data to a **remote** database that is **fully encrypted** by comdb.  The resulting database will have a mix of encrypted and unencrypted data.  I would like the unencrypted data to be encrypted upon syncing with user client application (without double encrypted existing data).

**Comment by garbados** [comment]
Hey hey, I've been pretty busy and haven't been able to get around to this yet. In the meantime, can you explain in more detail? I'm not sure I understand the step-by-step of your beginning state and desired end state. And, why would you want a database with a mix of encrypted and unencrypted data?
